### ISSUE TITLE
update landing page with gnark specific descriptions

### ISSUE THREAD

**Issue by gbotrel** [ConsenSys/doc.gnark#20]
#19 need a bit of polishing to update the landing page with gnark specific text (right now we the quick links section looks like for EthSigner;

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/11349757/216991905-df372055-2cb2-41b4-9bd4-8ea3afb110c0.png">

). 

Also few broken links for example: 
https://docs.gnark.consensys.net/Reference/api -_> "Front End" and "Back End" links are broken ( https://pkg.go.dev/github.com/consensys/gnark@%7B%7Bcontent_vars.gnark_version%7D%7D/frontend )

**Comment by yelhousni** [comment]
- It seems that latex/mathjax support is broken in the new version (using $$)
- The twitter icon redirects to ConsenSys account. It redirects instead to https://twitter.com/gnark_team (or both).

**Comment by Ezzahhh** [comment]
I have incorporated the fixes onto a new branch with a PR open: https://github.com/ConsenSys/doc.gnark/pull/23
